version: 2.1
jobs:
 build:
   machine:
     environment:
      - SHORT_HASH: $(echo $CIRCLE_SHA1 | cut -c -7)
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

     # build the application image
     - run: docker build -t arnaud290/python-oc-lettings-fr:$SHORT_HASH .

     # deploy the image
     - run: docker push arnaud290/python-oc-lettings-fr:$SHORT_HASH
