version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

     # build the application image
     - run: docker build -t arnaud290/python-oc-lettings-fr:$CIRCLE_HASH .

     # deploy the image
     - run: docker push arnaud290/python-oc-lettings-fr:$CIRCLE_BRANCH
