version: 2.1
jobs:
 build:
   docker:
      - image: circleci/golang:1.15
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS  # context / project UI env-var referen
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

     - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t arnaud290/python-oc-lettings-fr:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push arnaud290/python-oc-lettings-fr:$TAG