version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    steps:
     - checkout
     - run: |
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
          docker build -t arnaud290/python-oc-lettings-fr:$CIRCLE_SHA1 .
          docker push arnaud290/python-oc-lettings-fr:$CIRCLE_SHA1
  test:
    docker:
      - image: arnaud290/python-oc-lettings-fr:$CIRCLE_SHA1
    steps:
      - checkout
      - run: python ./manage.py test
 

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
