version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app
      - run:
          name: Build and push docker
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
            docker build -t arnaud290/python-oc-lettings-fr:$CIRCLE_SHA1 .
            docker push arnaud290/python-oc-lettings-fr:$CIRCLE_SHA1

#version: 2.1
#
## Define the jobs we want to run for this project
#jobs:
#  build:
#    machine: True
#    steps:
#     - checkout
#     - run: |
#          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
#          docker build -t arnaud290/python-oc-lettings-fr:$CIRCLE_SHA1 .
#          
#  test:
#    docker:
#      - image: arnaud290/python-oc-lettings-fr:$CIRCLE_SHA1
#        auth:
#          username: $DOCKER_USER
#          password: $DOCKER_PASS  # context / project UI env-var reference
#    steps:
#      - checkout
#      - run: |
#          python ./manage.py test
#
#  #deploy:
#  #  machine: True
#  #  steps:
#  #   - checkout
#  #   - run: |
#          
#          
# 
#
## Orchestrate our job run sequence
#workflows:
#  build_test:
#    jobs:
#      - build
#      - test:
#          requires:
#            - build
#
#
##docker push arnaud290/python-oc-lettings-fr:$CIRCLE_SHA1