version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    machine: True
    steps:
     - checkout
     - run: |
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
          docker build -t arnaud290/python-oc-lettings-fr:$CIRCLE_SHA1 .
          docker push arnaud290/python-oc-lettings-fr:$CIRCLE_SHA1
  test:
    docker:
      - image: arnaud290/python-oc-lettings-fr:$CIRCLE_SHA1
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS  # context / project UI env-var reference
    steps:
      - checkout
      - run: |
          python ./manage.py test

  #deploy:
  #  machine: True
  #  steps:
  #   - checkout
  #   - run: |
          
          
 

# Orchestrate our job run sequence
workflows:
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
