version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: arnaud290/python-oc-lettings-fr:$CIRCLE_SHA1
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS # context / project UI env-var reference
    steps:
      - checkout
      - run: docker build -t arnaud290/python-oc-lettings-fr:$CIRCLE_SHA1 .
  test:
    docker:
      - image: arnaud290/python-oc-lettings-fr:$CIRCLE_SHA1
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS  # context / project UI env-var reference
    steps:
      - checkout
      - run: python ./manage.py test
  deploy:
    docker:
      - image: arnaud290/python-oc-lettings-fr:$CIRCLE_SHA1
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS  # context / project UI env-var reference
    steps:
      - checkout
      - run: docker push arnaud290/python-oc-lettings-fr:$CIRCLE_SHA1

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
            - test
      - deploy:
          requires:
            - hold
