version: 2.1

# Define the jobs we want to run for this project
jobs:
  test:
    machine: 
      - python:
          version: 3.8
    steps:
      - checkout
      - run: |
          pip install -r ./requirements.txt
          python3 ./manage.py test
  build:
    machine: True
    steps:
     - checkout
     - run: |
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
          docker build -t arnaud290/python-oc-lettings-fr:$CIRCLE_SHA1 .
          docker push arnaud290/python-oc-lettings-fr:$CIRCLE_SHA1
  #deploy:
  #  machine: True
  #  steps:
  #   - checkout
  #   - run: |
  #        echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
  #        docker push arnaud290/python-oc-lettings-fr:$CIRCLE_SHA1
 

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
