version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py test
      #- store_artifacts:
      #    path: test-reports/
      #    destination: python_app
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
            docker build -t arnaud290/python-oc-lettings-fr:${CIRCLE_SHA1:0:7} .
            docker push arnaud290/python-oc-lettings-fr:${CIRCLE_SHA1:0:7}
  test:
    machine: True
    steps:
     - checkout
     - run: 
         name: Test Docker
         command: |
            docker run -d  -e "PORT=8000" -e "DEBUG=1" -p 8000:8000 arnaud290/python-oc-lettings-fr  
  deploy:
    machine: True
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
